# Site settings
title: UX Munich
email: hello@uxmunich.com
description: > # this means to ignore newlines until "baseurl:"
  A unique 2-day conference celebrating web technologies. Meet other web professionals to explore UX strategies and how to integrate them with modern web design and development.
keywords: user experience, conference, ux munich, web design, web development
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://uxmunich.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
